WIP: remove grm/ignore, unused args (leader election), poc to handle configuration from providerConfig, disable health check for a developoment, experiment with lifecycle preStop hook, remove uninstall script and use trap

diff --git a/charts/cri-resmgr-installation/templates/configmap.yaml b/charts/cri-resmgr-installation/templates/configmap.yaml
--- a/charts/cri-resmgr-installation/templates/configmap.yaml
+++ b/charts/cri-resmgr-installation/templates/configmap.yaml
@@ -17,9 +17,47 @@ kind: ConfigMap
 metadata:
   name: cri-resmgr-installation-script
   namespace: kube-system
-  annotations:
-    resources.gardener.cloud/ignore: "true"
+  #annotations:
+  #  resources.gardener.cloud/ignore: "true"
 data:
+  # WILL NOT WORK because restaring kubelet kills exec hook
+  uninstall-cri-resmgr.sh: |-
+    #!/bin/bash
+    # Remove cri-resmgr from kubelet configuration
+    echo "Remove cri-resmgr from kubelet configuration"
+    sed -i '/\[Unit\]/aAfter=containerd.service' /var/host/etc/systemd/system/kubelet.service
+    sed -i 's/\/var\/run\/cri-resmgr\/cri-resmgr.sock/unix:\/\/\/run\/containerd\/containerd.sock/g' /var/host/etc/systemd/system/kubelet.service
+
+    # Stop and disable cri-resource-manager
+    echo 'Stop and disable cri-resource-manager'
+    chroot /var/host bash -c "systemctl disable cri-resource-manager"
+    chroot /var/host bash -c "systemctl stop cri-resource-manager"
+
+    # Remove files left after cri-resmgr
+    echo 'Remove files left after cri-resmgr'
+    rm -rf /var/host/opt/intel
+    # replaced by mouting default file
+    rm -rf /var/host/etc/cri-resmgr
+    rm -rf /var/host/etc/systemd/system/cri-resource-manager.service
+
+    # Restart kubelet with new confugiration
+    echo 'Restart kubelet with new configuration'
+    chroot /var/host bash -c "systemctl daemon-reload"
+    chroot /var/host bash -c "systemctl restart kubelet"
+
+    # Check if kubelet is active
+    echo 'Check if kubelet is active'
+    while true; do
+        kubeletIsActive=$(chroot /var/host bash -c "systemctl is-active kubelet")
+        if [ "$kubeletIsActive" == "active" ];then
+            break
+        fi
+    done
+
+    # Sleep after successful removal 
+    echo 'Uninstallation successful. Sleeping...'
+    echo "cri-resource-manager successfully removed. Sleeping..."
+
   install-cri-resmgr.sh: |-
     #!/bin/bash
     # check if kubelet service file is a symlink
@@ -27,33 +65,106 @@ data:
       echo "err: kubelet.service file is a symlink"
       exit 1
     fi
-    cp -r /cri-resmgr-installation/opt/ /var/host/
-    cp -r /cri-resmgr-installation/etc/ /var/host/
-    cp /var/host/etc/cri-resmgr/fallback.cfg.sample /var/host/etc/cri-resmgr/fallback.cfg
-    chroot /var/host bash -c "systemctl enable cri-resource-manager"
-    chroot /var/host bash -c "systemctl restart cri-resource-manager"
-    sed -i  '/containerd/d' /var/host/etc/systemd/system/kubelet.service
-    if ! grep -q container-runtime-endpoint  "/var/host/etc/systemd/system/kubelet.service"; then
-      # matches GardenLinux kubelet config
-      sed '/KUBELET_EXTRA_ARGS \\/ s!$!\n    --container-runtime-endpoint=/var/run/cri-resmgr/cri-resmgr.sock\\!' -i /var/host/etc/systemd/system/kubelet.service
-      # matches kind-node kubelet config
-      sed '/KUBELET_EXTRA_ARGS$/ s!$! \\\n    --container-runtime-endpoint=/var/run/cri-resmgr/cri-resmgr.sock\\!' -i /var/host/etc/systemd/system/kubelet.service
-    fi
-    # Check if cri-resource-manager, containerd and kubelet is active
-    while true; do
-        criIsActive=$(chroot /var/host bash -c "systemctl is-active cri-resource-manager")
-        containerdIsActive=$(chroot /var/host bash -c "systemctl is-active containerd")
-        kubeletIsActive=$(chroot /var/host bash -c "systemctl is-active kubelet")
-        if [ "$criIsActive" == "active" ] && [ "$containerdIsActive" == "active" ] && [ "$kubeletIsActive" == "active" ];then
-            break
-        fi
-    done
-    # Restart kubelet
-    chroot /var/host bash -c "systemctl daemon-reload"
-    chroot /var/host bash -c "systemctl restart kubelet"
-    # Sleep after comlpeting the task
+    function install() {
+      echo Installing binaries from /opt/ to host /
+      cp -r /cri-resmgr-installation/opt/ /var/host/
+
+      echo Installing systemd unit
+      cp -v /cri-resmgr-installation/etc/systemd/system/cri-resource-manager.service  /var/host/etc/systemd/system/cri-resource-manager.service
+
+      echo Installing mounted configuration file from /etc/cri-resmgr/fallback.cfg to host /etc/cri-resmgr
+      # replaced by mouting default file
+      #cp -r /cri-resmgr-installation/etc/ /var/host/
+      #cp /var/host/etc/cri-resmgr/fallback.cfg.sample /var/host/etc/cri-resmgr/fallback.cfg
+      if [[ ! -f /etc/cri-resmgr/fallback.cfg ]]; then
+          echo "err: missing configuration file /var/host/etc/cri-resmgr/fallback.cfg"
+          exit 1
+      fi
+      mkdir -p /var/host/etc/cri-resmgr
+      cp -v /etc/cri-resmgr/fallback.cfg /var/host/etc/cri-resmgr/fallback.cfg
+
+      echo Enable and restart cri-resource-manager systemd unit.
+      chroot /var/host bash -c "systemctl enable cri-resource-manager"
+      chroot /var/host bash -c "systemctl restart cri-resource-manager"
+
+      echo Reconfigure kubelet.service to use connect to cri-resmgr.sock as container-runtime
+      sed -i  '/containerd/d' /var/host/etc/systemd/system/kubelet.service
+      if ! grep -q container-runtime-endpoint  "/var/host/etc/systemd/system/kubelet.service"; then
+        # matches GardenLinux kubelet config
+        sed '/KUBELET_EXTRA_ARGS \\/ s!$!\n    --container-runtime-endpoint=/var/run/cri-resmgr/cri-resmgr.sock\\!' -i /var/host/etc/systemd/system/kubelet.service
+        # matches kind-node kubelet config
+        sed '/KUBELET_EXTRA_ARGS$/ s!$! \\\n    --container-runtime-endpoint=/var/run/cri-resmgr/cri-resmgr.sock\\!' -i /var/host/etc/systemd/system/kubelet.service
+      fi
+      echo Wait for cri-resource-manager, container and kubelet services to be active
+      # Check if cri-resource-manager, containerd and kubelet is active
+      while true; do
+          criIsActive=$(chroot /var/host bash -c "systemctl is-active cri-resource-manager")
+          containerdIsActive=$(chroot /var/host bash -c "systemctl is-active containerd")
+          kubeletIsActive=$(chroot /var/host bash -c "systemctl is-active kubelet")
+          if [ "$criIsActive" == "active" ] && [ "$containerdIsActive" == "active" ] && [ "$kubeletIsActive" == "active" ];then
+              break
+          fi
+      done
+      echo Restart kubelet
+      chroot /var/host bash -c "systemctl daemon-reload"
+      chroot /var/host bash -c "systemctl restart kubelet"
+    }
+
+    function uninstall() {
+      # Remove cri-resmgr from kubelet configuration
+      echo "Remove cri-resmgr from kubelet configuration"
+      sed -i '/\[Unit\]/aAfter=containerd.service' /var/host/etc/systemd/system/kubelet.service
+      sed -i 's/\/var\/run\/cri-resmgr\/cri-resmgr.sock/unix:\/\/\/run\/containerd\/containerd.sock/g' /var/host/etc/systemd/system/kubelet.service
+
+      # Stop and disable cri-resource-manager
+      echo 'Stop and disable cri-resource-manager'
+      chroot /var/host bash -c "systemctl disable cri-resource-manager"
+      chroot /var/host bash -c "systemctl stop cri-resource-manager"
+
+      # Remove files left after cri-resmgr
+      echo 'Remove files left after cri-resmgr'
+      rm -rf /var/host/opt/intel
+      # replaced by mouting default file
+      rm -rf /var/host/etc/cri-resmgr
+      rm -rf /var/host/etc/systemd/system/cri-resource-manager.service
+
+      # Restart kubelet with new confugiration
+      echo 'Restart kubelet with new configuration'
+      chroot /var/host bash -c "systemctl daemon-reload"
+      chroot /var/host bash -c "systemctl restart kubelet"
+
+      # Check if kubelet is active
+      echo 'Check if kubelet is active'
+      while true; do
+          kubeletIsActive=$(chroot /var/host bash -c "systemctl is-active kubelet")
+          if [ "$kubeletIsActive" == "active" ];then
+              break
+          fi
+      done
+
+      # Sleep after successful removal 
+      echo 'Uninstallation successful. Sleeping...'
+      echo "cri-resource-manager successfully removed. Sleeping..."
+      kill -KILL "$child" 2>/dev/null
+    }
+
+    # Install cri-rm
+    install
+
+    #echo "Setup termination handler."
+    trap uninstall SIGTERM SIGINT
+
+    # Sleep after installation the task
     echo "cri-resource-manager installed. Sleeping..."
     while true; do
-      sleep 3600;
+      # put sleep in background and wait to allow bash to capture and handle signals
+      # based on https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash
+      # consider using postHook handler
+      # https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
+      sleep 3600 &
+      child=$!
+      wait $child
       echo "Still sleeping...";
     done
+
+
